services:
  # mysqldb:
  #   image: mysql:latest
  #   container_name: mysql
  #   ports:
  #     - 3306:3306

  #   volumes:
  #     - /home/master/.mysql-docker:/var/lib/mysql
    
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=mypassword
  #     - MYSQL_DATABASE=evoai

  postgresdb:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - 5432:5432
    
    volumes:
      - /home/master/.postgres_docker:/var/lib/postgresql/data

    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=evoai

# docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d -v postgres_data:/var/lib/postgresql/data postgres
